# Generated by Django 4.1.7 on 2023-08-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('role', models.CharField(default='user', max_length=50)),
                ('status', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
