# Generated by Django 4.1.7 on 2023-08-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemp', '0005_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
