# Generated by Django 4.1.7 on 2023-08-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemp', '0008_developer_image_teamlead_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='teamlead',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teamlead',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teamlead',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
    ]
