# Generated by Django 4.1.7 on 2023-08-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemp', '0009_project_teamlead_alter_developer_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=255, null=True)),
                ('tlname', models.CharField(max_length=255, null=True)),
                ('date', models.DateField(null=True)),
                ('progress', models.CharField(max_length=255, null=True)),
                ('remarks', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
