# Generated by Django 4.1.7 on 2023-08-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemp', '0010_dailyprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='document',
            field=models.FileField(null=True, upload_to='pdfs/'),
        ),
    ]
