# Generated by Django 4.1.7 on 2023-08-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemp', '0012_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='file',
            field=models.FileField(null=True, upload_to='pdfs/'),
        ),
    ]
