# Generated by Django 4.1.7 on 2023-08-27 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemp', '0013_module_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('progress', models.CharField(max_length=255, null=True)),
                ('remarks', models.CharField(max_length=255, null=True)),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itemp.module')),
            ],
        ),
    ]
