# Generated by Django 4.1.7 on 2023-09-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemp', '0016_alter_otp_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=255, null=True)),
                ('tlname', models.CharField(max_length=255, null=True)),
                ('date', models.DateField(null=True)),
                ('file', models.FileField(null=True, upload_to='pdfs/')),
                ('remarks', models.CharField(max_length=255, null=True)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
