# Generated by Django 4.1.7 on 2023-09-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemp', '0017_projectprogress_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=255, null=True)),
                ('module', models.CharField(max_length=255, null=True)),
                ('devname', models.CharField(max_length=255, null=True)),
                ('date', models.DateField(null=True)),
                ('file', models.FileField(null=True, upload_to='pdfs/')),
                ('remarks', models.CharField(max_length=255, null=True)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
